site:
  title: ThoughtSpot Documentation
  url: https://docs-test-thoughtspot.netlify.app
  start_page: home::index.adoc
content:
  sources:
  # embedding empty credentials in the URL disables the Edit this Page link for any page created from this repository
  - url: .
    branches: HEAD
    start_path: home
  - url: git@github.com:thoughtspot/thoughtspot-docs.git
    branches: ['6.0', '6.1', '6.2', '6.3', '7.0', '7.1', '7.2', '8.4.1.sw']
    start_path: software/
  - url: git@github.com:thoughtspot/thoughtspot-docs.git
    branches: ['8.4.0.cl', '8.7.0.cl', '8.9.0.cl', '8.10.0.cl', '9.0.0.cl', '9.2.0.cl']
    start_path: cloud/
  - url: git@github.com:thoughtspot/thoughtspot-docs.git
    branches: ['seekwell']
    start_path: seekwell/
  - url: git@github.com:thoughtspot/visual-embed-sdk.git
    branches: ['7.1.1-sw-docs', '7.2-sw-docs']
    start_path: docs/software
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: latest
  html_extension_style: drop
ui:
  bundle:
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    url: ui-bundle/ui2-bundle.zip
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"
    snapshot: true
asciidoc:
  attributes:
    #software: true
    #cloud: false
    page-company: ThoughtSpot
    tabs: tabs
    seekwell: SeekWell
    support-url: https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support^]
  extensions:
  - ./lib/asciidoctor-performance-patch.js
  - "@djencks/asciidoctor-tabset-block"
  - "@djencks/asciidoctor-glossary"
output:
  clean: true
  dir: build/
runtime:
  fetch: true
  log:
    level: error
